#!/bin/bash

if [ $# -ne 5 ];then
	echo "Not enough arguements">&2
	exit
fi

for i; do
	if [ $i -eq 0 ] || [ $i -gt 10 ];then
		echo "illegal grade 0 or>10 as input">&2
		exit
	fi
sum=$((sum + $i))
done

if [ $sum -lt 5 ];then
	echo "Come on September"
elif awk "BEGIN {exit !($sum <= 7.5)}";then
	echo "Good"
else
	echo "Excellent"
fi
